version: '3.8'

services:
  # PostgreSQL Database
  db:
    image: postgres:15-alpine
    container_name: monolith-db
    environment:
      POSTGRES_DB: monolith_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - monolith-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Backend Server
  server:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: monolith-server
    environment:
      DENO_ENV: production
      PORT: 4000
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: monolith_db
      DB_USER: postgres
      DB_PASSWORD: postgres
    ports:
      - "4000:4000"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - monolith-network
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local

networks:
  monolith-network:
    driver: bridge 